version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 挂载Docker socket文件
      - /home/ying01li/kalib_service/uploads:/app/uploads
    environment:
      - NODE_ENV=development
